# Generated by Django 5.1.1 on 2024-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=3)),
                ('discription', models.TextField()),
            ],
        ),
    ]
