# Generated by Django 5.1.1 on 2024-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vedamusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
