# Generated by Django 5.1.1 on 2024-10-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vedamusic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vedamusic',
        ),
    ]
